name: "SABnzbd K8s: Publish"

on:
  workflow_call:
    inputs:
      dry-run:
        type: boolean
        default: false

jobs:
  quality:
    uses: charmarr/.github/.github/workflows/charm-ci.yaml@v1
    with:
      charm-path: charms/sabnzbd-k8s

  publish:
    needs: quality
    uses: charmarr/.github/.github/workflows/charm-publish.yaml@v1
    with:
      charm-path: charms/sabnzbd-k8s
      channel: latest/edge
      dry-run: ${{ inputs.dry-run || false }}
    secrets:
      CHARMHUB_TOKEN: ${{ secrets.CHARMHUB_TOKEN }}
      WIREGUARD_PRIVATE_KEY: ${{ secrets.WIREGUARD_PRIVATE_KEY }}
